- name: Deploy the ORA Grading MFE Frontend
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'ora-grading'
    ORA-GRADING_ENABLED: True
    ORA-GRADING_SANDBOX_BUILD: False
  roles:
    - role: mfe
      MFE_NAME: ora_grading
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELICE_INFRASTRUCTURE

